name: AWS Build and Deploy All
on:
  workflow_dispatch:
    branches: [ main ]
jobs:
    backend:
        uses: mfuqua3/MrWorldWide/.github/workflows/backend.yml@main
        secrets: inherit
    frontend:
        needs: backend
        uses: mfuqua3/MrWorldWide/.github/workflows/frontend.yml@main
        secrets: inherit